<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-O94L9J6" name="com.training.ComplexTestCases.tests.RETC078_AddUserInvalidDetails_AdminTest" tests="4" failures="0" timestamp="2019-12-05T15:55:27 IST" time="27.669" errors="1">
  <testcase name="adminLogin" time="7.335" classname="com.training.ComplexTestCases.tests.RETC078_AddUserInvalidDetails_AdminTest"/>
  <testcase name="addAndViewUsers" time="5.179" classname="com.training.ComplexTestCases.tests.RETC078_AddUserInvalidDetails_AdminTest"/>
  <testcase name="addAndViewUsers" time="3.411" classname="com.training.ComplexTestCases.tests.RETC078_AddUserInvalidDetails_AdminTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at org.openqa.selenium.support.ui.Quotes.escape(Quotes.java:42)
at org.openqa.selenium.support.ui.Select.selectByVisibleText(Select.java:116)
at com.training.pom.NewUserPOM.addNewUser(NewUserPOM.java:88)
at com.training.ComplexTestCases.tests.RETC078_AddUserInvalidDetails_AdminTest.addAndViewUsers(RETC078_AddUserInvalidDetails_AdminTest.java:94)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- addAndViewUsers -->
  <testcase name="addAndViewUsers" time="11.744" classname="com.training.ComplexTestCases.tests.RETC078_AddUserInvalidDetails_AdminTest"/>
</testsuite> <!-- com.training.ComplexTestCases.tests.RETC078_AddUserInvalidDetails_AdminTest -->
